<a href="https://colab.research.google.com/github/Jayyanth-21/COE/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [5]:
a1=np.array([12,84,6,43,56,25,100])
a1.sort()
a1

array([  6,  12,  25,  43,  56,  84, 100])

In [9]:
a2=np.array([[21,18,3],[2,56,4]])
a2

array([[21, 18,  3],
       [ 2, 56,  4]])

In [11]:
  np.arange(0,18,3)

array([ 0,  3,  6,  9, 12, 15])

In [12]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)


(2, 3)
